### PR TITLE
Cookie icon button

### PR DESCRIPTION
**Pull request by BNewing**
Things to do: 

- [x] Add in new cookie icon button
- [x] Add in the JS so that it toggles the banner being shown
- [x] Hook it up so that if a user that had previously said 'yes' to cookies now says 'no', it respects this choice
- [x] Cross-browser test (Firefox, Chrome, Safari, IE, Edge)

After review:
- [x] Make toggle reflect current GA cookie status

### CODE REVIEW

**Comment by brown-a2** [comment]
Working very nicely. I am getting one issue, where if I click accept all cookies, refresh the page and then click on the corner button, the on/off toggle in the model for GA doesn't show true it is still stuck in the "off" position.

**Comment by BNewing** [comment]
Thank you for taking a look Adam! I'd not actually thought about that as a thing to do, I'll take a look at that now.

**Comment by brown-a2** [comment]
I think... you either need to add something in the acceptAllButton that sets the toggle to on... or better have the toggle check what the cookie setting is set to, as a way to inform it's position.. maybe you have it and I've missed it.

**Comment by BNewing** [comment]
I will take a look. It currently isn't doing it, I'd not thought of that scenario so thank you for flagging!

**Comment by brown-a2** [comment]
That was the only issue I found so once that's fixed, I think this is good to go.

**Comment by brown-a2** [comment]
I think what you've added needs to be under the acceptAllButton function. So that if the accept al button is pressed, the toggle is also set to true?

**Comment by BNewing** [comment]
I've now put it into the method that shows the modal, so that turning it to the correct state is part of what happens when it loads up :)

**Comment by brown-a2** [comment]
Great, merge away 👍

**Review by brown-a2 — APPROVED** [review]

**Pull request merged**
